version: '2.9'

name: pokeclj-dev

services:
  # TODO: frontend app
  api:
    build:
      context: ./apisvc
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "pokeclj_db"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5432"
      SYNC_BASE_URL: "https://pokeapi.co/api/v2/"
    restart: always
    ports:
      - 4399:4399
    depends_on:
      - db
  db:
    build:
      context: ./db
      args:
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "pass"
        POSTGRES_DB: "pokeclj_db"
        POSTGRES_DATA: "./pgdata-dev"
        POSTGRES_HOST: "db"
        POSTGRES_PORT: "5432"
    restart: always
    volumes:
      - ./pgdata-dev:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pokeclj_db"]
      interval: 10s
      timeout: 5s
      retries: 3
  migrate:
    image: migrate/migrate:latest
    profiles: ["tools"]
    volumes:
      - ./db/migrations:/migrations
    entrypoint: [
      "migrate",
      "-path",
      "/migrations",
      "-database",
      "postgres://admin:pass@db:5432/pokeclj_db?sslmode=disable"
    ]
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
