version: '2.9'

name: pokeclj

services:
  # TODO: frontend app
  api:
    build:
      context: ./apisvc
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_DATA: "${POSTGRES_DATA}"
      SYNC_BASE_URL: "https://pokeapi.co/api/v2/"
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
      - db
  db:
    build:
      context: ./db
      args:
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_DATA: "${POSTGRES_DATA}"
    restart: always
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
  migrate:
    image: migrate/migrate:latest
    profiles: ["tools"]
    volumes:
      - ./db/migrations:/migrations
    networks:
      - backend
    entrypoint: [
      "migrate",
      "-path",
      "/migrations",
      "-database",
      "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
    ]
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
